### ISSUE TITLE
移动端优化点

### ISSUE THREAD

**Issue by yevolcn** [o2team/UFT#10]
## 20151215

1. [x] 头部加JDC logo
2. [x] 尾部O2TEAM改为“JDC多终端研发部”
3. [x] 需求提交申请，标识字段：需求名称
4. [x] 右上角菜单自动收起
5. [x] 提交需求按钮调大
6. [x] 隐藏排期表
7. [x] 需求详情隐藏提交人头像
8. [x] 附件上传按钮居中
9. [x] "我的"tab样式兼容
10. [x] 隐藏个人资料页
11. [x] 广场页 列表宽度调整
12. [x] 右上角菜单展开时文案调整为“关闭”

**Comment by Manjiz** [comment]
隐藏个人资料页：只显示部分个人资料

**Comment by Manjiz** [comment]
@Newcandy
